'use client';

/**
 * /simulation — counterfactual surface for the MBP loop.
 *
 * Two scoped entry points are supported (FR-SM-1):
 *   1. Growth-driver stress-test
 *      ?study=<id>&driver=<driver_id>&must_do=<must_do_slug>&prompt=<prompt>
 *      Prompts (typed set generated by /growth-driver Column C):
 *        - flip-fragile-assumption
 *        - cut-ap-30
 *        - add-competitor-response
 *        - alternative-driver
 *        - in-year-since-last-quarter (opens the committed decision's
 *          in-year diff when one exists)
 *      When ?prompt is omitted the page falls back to the generic
 *      concentrate-vs-extend framing.
 *   2. Research-finding counter-scenario
 *      ?study=<id>&finding=<idx>&prompt=<heuristic>&occasion=<o>&brand=<b>
 *      Existing supported prompt: discount-vs-bundle.
 *
 * The page renders ≥2 counterfactual variants for the active scope
 * (FR-SM-3), each with a directional effect, an inputs panel naming
 * the actual data sources, an honest confidence pill, and an
 * "assumes / doesn't assume" disclosure. The math behind the
 * projection is printed in the disclosure so it stays defensible
 * (NFR-2: honest illustrative).
 *
 * Two CTAs are wired:
 *   - "Validate against promo data" — POST /tasks(kind=validate-promo)
 *   - "Commit as decision" — POST /counterfactuals then POST /decisions,
 *     redirecting to /decision/[id].
 */

import Link from 'next/link';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import {
  AlertTriangle,
  ArrowRight,
  Beaker,
  CheckCircle2,
  Compass,
  FileSearch,
  HelpCircle,
  Info,
  Send,
  Sparkles,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { ConfidencePanel } from '@/components/study/confidence-panel';
import { FocusCard, StudyShell } from '@/components/study/study-shell';
import { useStudyData, withStudy } from '@/components/study/use-study';
import { PaneCard } from '@/components/workbench/pane-layout';
import { cn } from '@/lib/utils';
import {
  wb,
  type AssetSummary,
  type CounterfactualScopeBody,
  type DecisionScopeBody,
  type GrowthDriverDTO,
  type MustDoDTO,
  type ResearchSummary,
  type TaskScopeBody,
} from '@/components/workbench/types';

type DriverScope = {
  kind: 'driver';
  driverSlug: string;
  driverLabel: string;
  mustDoSlug: string | null;
  mustDoLabel: string | null;
  prompt: string | null;
};

type FindingScope = {
  kind: 'finding';
  findingIndex: number;
  prompt: string;
  promptLabel: string;
  occasion: string | null;
  brand: string | null;
};

type EmptyScope = { kind: 'empty' };

type Scope = DriverScope | FindingScope | EmptyScope;

type ConfidenceLevel = 'Low' | 'Medium' | 'High';

type EvidenceInput = { label: string; source: string };

type Variant = {
  id: string;
  title: string;
  subtitle: string;
  directional: string;
  effectValue: string;
  effectKind: 'lift' | 'hold' | 'hedge' | 'risk';
  confidence: ConfidenceLevel;
  confidenceReason: string;
  inputs: EvidenceInput[];
  assumes: string[];
  doesNotAssume: string[];
  math: string;
  illustrative: boolean;
};

type CommitState =
  | { kind: 'idle' }
  | { kind: 'pending'; stage: 'counterfactual' | 'decision' }
  | { kind: 'error'; message: string };

type ValidateState =
  | { kind: 'idle' }
  | { kind: 'pending' }
  | {
      kind: 'success';
      taskId: string;
      assetKeyEncoded: string;
    }
  | { kind: 'error'; message: string };

// Hardcoded for the single seeded MBP. Mirrors the descriptor that
// /api/decisions stamps on a committed decision when its scope names a
// driver_id, so the simulation page can render the same MBP-scope copy
// before commit.
const SEEDED_MBP_NAME = 'Crown Royal × NFL 2026-27 MBP';

function SimulationBody() {
  const data = useStudyData();
  const { studyId, curve, detail } = data;
  const router = useRouter();
  const search = useSearchParams();
  const [summary, setSummary] = useState<ResearchSummary | null>(null);
  const [growthDrivers, setGrowthDrivers] = useState<{
    studyId: string | null;
    drivers: GrowthDriverDTO[];
    mustDos: MustDoDTO[];
  }>({ studyId: null, drivers: [], mustDos: [] });
  const [toast, setToast] = useState<{
    id: number;
    title: string;
    body: string;
  } | null>(null);
  const [validateState, setValidateState] = useState<ValidateState>({
    kind: 'idle',
  });
  const [commitState, setCommitState] = useState<CommitState>({ kind: 'idle' });

  useEffect(() => {
    if (!studyId) return;
    let cancelled = false;
    wb.research(studyId)
      .then((s) => {
        if (!cancelled) setSummary(s);
      })
      .catch(() => {
        if (!cancelled) setSummary(null);
      });
    return () => {
      cancelled = true;
    };
  }, [studyId]);

  // Fetch the planning-context drivers when scoped to a driver, so the
  // ScopeCard can render the MBP descriptor (mbp · must_do · driver)
  // instead of the underlying study question.
  useEffect(() => {
    if (!studyId) return;
    let cancelled = false;
    wb.growthDrivers(studyId)
      .then((res) => {
        if (cancelled) return;
        setGrowthDrivers({
          studyId,
          drivers: res.drivers ?? [],
          mustDos: res.must_dos ?? [],
        });
      })
      .catch(() => {
        if (cancelled) return;
        setGrowthDrivers({ studyId, drivers: [], mustDos: [] });
      });
    return () => {
      cancelled = true;
    };
  }, [studyId]);

  // Drop the cached research summary when the study switches so we
  // never render stale finding data against a new study scope.
  const summaryForStudy = studyId ? summary : null;

  useEffect(() => {
    if (!toast) return;
    const t = window.setTimeout(() => setToast(null), 5200);
    return () => window.clearTimeout(t);
  }, [toast]);

  const driverParam = search.get('driver');
  const mustDoParam = search.get('must_do');
  const findingParam = search.get('finding');
  const promptParam = search.get('prompt');
  const occasionParam = search.get('occasion');
  const brandParam = search.get('brand');

  const scope = useMemo<Scope>(
    () =>
      deriveScope({
        driver: driverParam,
        mustDo: mustDoParam,
        finding: findingParam,
        prompt: promptParam,
        occasion: occasionParam,
        brand: brandParam,
      }),
    [
      driverParam,
      mustDoParam,
      findingParam,
      promptParam,
      occasionParam,
      brandParam,
    ],
  );

  const findingTitle = useMemo(() => {
    if (scope.kind !== 'finding') return null;
    if (summaryForStudy && summaryForStudy.top_risks.length > scope.findingIndex) {
      return summaryForStudy.top_risks[scope.findingIndex]?.line ?? null;
    }
    return null;
  }, [scope, summaryForStudy]);

  const variants = useMemo(
    () => buildVariants(scope, findingTitle),
    [scope, findingTitle],
  );

  const headingTitle = buildTitle(scope, findingTitle);
  const headingIntro = buildIntro(scope);

  // FR-SM-4: POST /tasks(kind='validate-promo') and surface the resulting
  // task asset id inline so a planner can deep-link to it. Scope carries
  // study_id plus driver_id or a synthetic finding_id derived from the
  // finding index (the backend's TaskScope accepts both).
  const onValidatePromo = async () => {
    if (!studyId || variants.length === 0 || scope.kind === 'empty') return;
    setValidateState({ kind: 'pending' });
    try {
      const res = await wb.postTask({
        kind: 'validate-promo',
        scope: buildTaskScope(studyId, scope),
        due_date: null,
        description: buildValidateDescription(scope, findingTitle),
      });
      setValidateState({
        kind: 'success',
        taskId: res.task_id,
        assetKeyEncoded: res.asset_key_encoded,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setValidateState({ kind: 'error', message });
    }
  };

  // FR-SM-5: POST /counterfactuals to persist the chosen variant, then
  // POST /decisions referencing the resulting cf_id, then redirect to
  // /decision/[id]. We commit the "winning" variant (highest effect on
  // spend retention) because the readout already names it as the
  // recommendation — keeps the action consistent with what the user
  // sees. owner is hardcoded 'tim' for now; wire to auth later.
  const onCommitDecision = async () => {
    if (!studyId || variants.length === 0 || scope.kind === 'empty') return;
    const winner = pickWinner(variants);
    if (!winner) return;
    setCommitState({ kind: 'pending', stage: 'counterfactual' });
    try {
      const cfScope = buildCounterfactualScope(studyId, scope);
      const cfRes = await wb.postCounterfactual({
        study_id: studyId,
        scope: cfScope,
        prompt: buildCounterfactualPrompt(scope, findingTitle, winner),
        variants: [variantToBody(winner)],
        inputs: winner.inputs.map((i) => ({
          label: i.label,
          source: i.source,
        })),
        confidence_per_variant: [
          { variant_id: winner.id, confidence_pill: winner.confidence },
        ],
        assumes: winner.assumes,
        does_not_assume: winner.doesNotAssume,
      });

      setCommitState({ kind: 'pending', stage: 'decision' });
      const decRes = await wb.postDecision({
        scope: buildDecisionScope(studyId, scope),
        recommendation: buildRecommendation(scope, winner),
        confidence: deriveConfidenceBlock(winner),
        fragile_assumption: deriveFragileAssumption(scope, winner),
        counterfactual_refs: [cfRes.cf_id],
        inputs_used: winner.inputs.map((i) => i.source),
        // TODO: derive owner from auth when it lands.
        owner: 'tim',
      });
      // Redirect to the decision detail page (M4 / FR-DC-1).
      router.push(`/decision/${decRes.decision_id}?study=${studyId}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setCommitState({ kind: 'error', message });
    }
  };

  return (
    <>
      <StudyShell
        data={data}
        eyebrow="Counter-scenario simulation"
        title={headingTitle}
        intro={headingIntro}
        contentClassName="max-w-[1400px]"
        mainLabel="Counterfactual variants"
        rightLabel="Honest summary"
          main={
          !studyId ? null : scope.kind === 'empty' ? (
            <EmptyState detail={detail?.question ?? null} />
          ) : scope.kind === 'driver' &&
            scope.prompt === 'in-year-since-last-quarter' ? (
            <InYearHandoff
              studyId={studyId}
              driverSlug={scope.driverSlug}
              driverLabel={scope.driverLabel}
            />
          ) : (
            <div className="grid gap-4">
              <ScopeCard
                scope={scope}
                findingTitle={findingTitle}
                mbpDescriptor={
                  scope.kind === 'driver'
                    ? buildScopeMbpDescriptor(scope, growthDrivers)
                    : null
                }
              />
              <VariantsGrid variants={variants} />
              <DisclosureBlock variants={variants} scope={scope} />
              <ActionBar
                onValidatePromo={onValidatePromo}
                onCommitDecision={onCommitDecision}
                disabled={variants.length === 0}
                validateState={validateState}
                commitState={commitState}
              />
            </div>
          )
        }
        right={
          !studyId ? null : (
            <ConfidencePanel
              curve={curve}
              interval={{
                kind: 'prediction interval',
                available: false,
                requiredData:
                  scope.kind === 'finding' && scope.occasion
                    ? `connected promo, loyalty, and holdout outcomes for ${scope.occasion}.`
                    : 'connected promo, loyalty, and holdout outcomes for this study scope.',
              }}
              provenance={{
                source:
                  scope.kind === 'driver'
                    ? 'Growth-driver fixture + prereg traces'
                    : 'Research finding + study brief traces',
                transformation:
                  'Elasticity prior plus linear bundling uplift (printed in disclosure)',
                output:
                  'Per-variant directional effect, named inputs, honest confidence',
                available: variants.length > 0,
              }}
              raiseConfidence={[
                'Run /tasks → validate-against-promo to attach a real holdout for the active variant.',
                'Commit the chosen variant as a decision so the in-year diff can compare against new evidence later.',
                'Re-run the simulation after Worker B wires POST /counterfactuals so projections persist as assets.',
              ]}
            />
          )
        }
      />
      {toast ? (
        <Toast
          key={toast.id}
          title={toast.title}
          body={toast.body}
          onClose={() => setToast(null)}
        />
      ) : null}
    </>
  );
}

export default function SimulationPage() {
  return (
    <Suspense fallback={null}>
      <SimulationBody />
    </Suspense>
  );
}

function deriveScope(args: {
  driver: string | null;
  mustDo: string | null;
  finding: string | null;
  prompt: string | null;
  occasion: string | null;
  brand: string | null;
}): Scope {
  const { driver, mustDo, finding, prompt, occasion, brand } = args;
  if (driver) {
    return {
      kind: 'driver',
      driverSlug: driver,
      driverLabel: prettify(driver),
      mustDoSlug: mustDo,
      mustDoLabel: mustDo ? prettify(mustDo) : null,
      prompt: prompt?.trim() || null,
    };
  }
  if (finding != null) {
    const idxRaw = Number(finding);
    const findingIndex = Number.isFinite(idxRaw) && idxRaw >= 0 ? idxRaw : 0;
    const promptSlug = prompt?.trim() || 'discount-vs-bundle';
    return {
      kind: 'finding',
      findingIndex,
      prompt: promptSlug,
      promptLabel: prettify(promptSlug),
      occasion: occasion?.trim() ? prettify(occasion.trim()) : null,
      brand: brand?.trim() ? prettify(brand.trim()) : null,
    };
  }
  return { kind: 'empty' };
}

// Resolve the planning-context descriptor (MBP · Must-Do · Driver)
// for a driver-scoped counterfactual. Falls back to the slug-derived
// label when the growth-drivers fetch hasn't landed yet so the card
// never renders blank.
function buildScopeMbpDescriptor(
  scope: DriverScope,
  payload: {
    studyId: string | null;
    drivers: GrowthDriverDTO[];
    mustDos: MustDoDTO[];
  },
): ScopeMbpDescriptor {
  const driverRow = payload.drivers.find(
    (d) => d.driver_id === scope.driverSlug,
  );
  const mustDoId = driverRow?.must_do || scope.mustDoSlug || '';
  const mustDoRow = payload.mustDos.find((m) => m.id === mustDoId);
  return {
    mbpName: SEEDED_MBP_NAME,
    mustDo: mustDoRow?.title || scope.mustDoLabel || '',
    driver: driverRow?.driver_name || scope.driverLabel,
  };
}

// Title-case kebab/snake fragments, but keep small connectors lowercase
// when they sit between two real words (e.g. "discount-vs-bundle" →
// "Discount vs Bundle"). Used for brand/occasion/prompt labels coming
// from URL params, so the H1 reads like prose instead of slugs.
function prettify(slug: string): string {
  if (!slug) return '';
  const words = slug
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean);
  if (words.length === 0) return '';
  const SMALL = new Set(['vs', 'and', 'or', 'of', 'the', 'a', 'an', 'in']);
  return words
    .map((w, i) => {
      const lower = w.toLowerCase();
      if (i > 0 && i < words.length - 1 && SMALL.has(lower)) return lower;
      return lower[0].toUpperCase() + lower.slice(1);
    })
    .join(' ');
}

// Per-prompt title + intro copy for driver-scoped stress-tests. The
// labels here MUST match the wording in /growth-driver Column C's
// stress-test buttons so the page reads continuously left to right.
const DRIVER_PROMPT_COPY: Record<
  string,
  { title: string; intro: string }
> = {
  'flip-fragile-assumption': {
    title:
      'If our fragile assumption is wrong, does the driver still hold?',
    intro:
      'Variant A: assumption holds (baseline driver lift). Variant B: assumption flipped — the driver weakens or is replaced.',
  },
  'cut-ap-30': {
    title: 'Does this driver still hold with a 30% A&P cut?',
    intro:
      'Variant A: full A&P. Variant B: 30% A&P cut showing reach and frequency decay against the same goal.',
  },
  'add-competitor-response': {
    title:
      'If competitors step up in the focus markets, does our advantage compress?',
    intro:
      'Variant A: status quo. Variant B: a competitor lift in the focus markets that compresses our advantage.',
  },
  'alternative-driver': {
    title: 'What if we put this A&P behind a peer driver instead?',
    intro:
      'Variant A: this driver. Variant B: a peer driver inside the same Must-Do that could absorb the spend.',
  },
  'in-year-since-last-quarter': {
    title: 'What changed in-year since the last quarter?',
    intro:
      'Opens the in-year evidence diff against the committed decision for this driver, when one exists.',
  },
};

function buildTitle(scope: Scope, findingTitle: string | null): string {
  if (scope.kind === 'driver') {
    const promptCopy = scope.prompt ? DRIVER_PROMPT_COPY[scope.prompt] : null;
    if (promptCopy) return promptCopy.title;
    if (scope.mustDoLabel) {
      return `Stress-test: ${scope.driverLabel} · ${scope.mustDoLabel}`;
    }
    return `Stress-test: ${scope.driverLabel}`;
  }
  if (scope.kind === 'finding') {
    const subject = findingTitle?.trim() || `Finding #${scope.findingIndex + 1}`;
    const trimmed = subject.length > 90 ? `${subject.slice(0, 87)}…` : subject;
    if (scope.brand && scope.occasion) {
      return `Counter-scenario: ${scope.promptLabel} for ${scope.brand} in ${scope.occasion}`;
    }
    if (scope.occasion) {
      return `Counter-scenario: ${scope.promptLabel} in ${scope.occasion}`;
    }
    return `Counter-scenario: ${trimmed}`;
  }
  return 'Counter-scenario simulation';
}

function buildIntro(scope: Scope): string {
  if (scope.kind === 'driver') {
    const promptCopy = scope.prompt ? DRIVER_PROMPT_COPY[scope.prompt] : null;
    if (promptCopy) return promptCopy.intro;
    return 'Two defensible framings of the growth driver, with the math, the inputs, and the honest confidence each one earns. Use the actions at the bottom to validate against promo data or commit the chosen variant as a decision.';
  }
  if (scope.kind === 'finding') {
    // The H1 already names the prompt + brand + occasion, so the
    // intro line would just paraphrase it. Drop it.
    return '';
  }
  return 'Open this page from a growth driver or a research finding to scope a counterfactual.';
}

function buildVariants(
  scope: Scope,
  findingTitle: string | null,
): Variant[] {
  if (scope.kind === 'driver') {
    return buildDriverVariants(scope);
  }
  if (scope.kind === 'finding') {
    return buildFindingVariants(scope, findingTitle);
  }
  return [];
}

const DRIVER_INPUTS: EvidenceInput[] = [
  {
    label: 'Loyalty cohort flows',
    source: 'runs/loyalty_panel.csv (loyalty asset)',
  },
  {
    label: 'Brand-level elasticity prior',
    source: 'runs/elasticity_note.md (elasticity asset)',
  },
  {
    label: 'Occasion volume shares',
    source: 'runs/occasion_mix.json (occasion_share asset)',
  },
];

function buildDriverVariants(scope: DriverScope): Variant[] {
  const drv = scope.driverLabel;
  const mustDo = scope.mustDoLabel ?? 'this Must-Do';
  // Math constants — defensible toy priors. Worker B will replace these
  // with real elasticity numbers when POST /counterfactuals is wired
  // up. The values stay illustrative; the formula does not.
  const baseLift = 6;
  const elasticityPrior = 0.4;
  const bundlingUplift = 2.5;
  const apDecay = 0.35; // pp lost per 10pp of A&P cut (illustrative)
  const competitorPressure = 4.5; // pp absorbed by a competitor pulse (illustrative)

  switch (scope.prompt) {
    case 'flip-fragile-assumption':
      return [
        {
          id: 'assumption-holds',
          title: 'Assumption holds (baseline)',
          subtitle: `${drv} works because the fragile assumption holds in ${mustDo}.`,
          directional:
            'Baseline driver lift — assumes the fragile assumption named on the planner is true in-market.',
          effectValue: `+${baseLift.toFixed(1)} pp spend retention`,
          effectKind: 'hold',
          confidence: 'Medium',
          confidenceReason:
            'Elasticity prior is brand-level, not desk-level. Baseline assumes the planner-recorded fragile assumption is true.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'The fragile assumption on the planner holds in-market during the activation window.',
            'Focus markets carry the bulk of occasion volume.',
            'No new competitor pulse displaces shelf during the window.',
          ],
          doesNotAssume: [
            'A national rollout — scope stays inside the focus market list.',
            'Connected promo holdout data — none is wired yet.',
            'That the fragile assumption stays true beyond the window.',
          ],
          math: `retention_baseline = baseline + ${baseLift.toFixed(1)} pp; elasticity prior α = ${elasticityPrior}.`,
          illustrative: true,
        },
        {
          id: 'assumption-flipped',
          title: 'Assumption flipped (driver weakens)',
          subtitle: `${drv} weakens because the fragile assumption fails.`,
          directional:
            'If the assumption fails, the driver either collapses to a small residual lift or has to be replaced by a peer driver.',
          effectValue: `+${Math.max(baseLift - 4.5, 0).toFixed(1)} pp spend retention`,
          effectKind: 'risk',
          confidence: 'Low',
          confidenceReason:
            'No measured outcome data for the flipped case — the residual lift is a planning prior, not a measurement.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'The flipped assumption removes most of the lift but leaves a small residual from existing distribution.',
            'A peer driver in the same Must-Do could pick up the spend without a new planning round.',
          ],
          doesNotAssume: [
            'A specific peer driver — the alternative-driver prompt explores that.',
            'A clean cut to zero — the residual lift acknowledges baseline distribution.',
          ],
          math: `retention_flipped = baseline + max(${baseLift.toFixed(1)} − 4.5, 0) pp.`,
          illustrative: true,
        },
      ];
    case 'cut-ap-30':
      return [
        {
          id: 'full-ap',
          title: 'Full A&P (baseline)',
          subtitle: `${drv} runs with the planned A&P allocation inside ${mustDo}.`,
          directional:
            'Baseline reach and frequency; the driver carries the lift it was scoped to deliver.',
          effectValue: `+${baseLift.toFixed(1)} pp spend retention`,
          effectKind: 'hold',
          confidence: 'Medium',
          confidenceReason:
            'Elasticity prior is brand-level. Reach and frequency assumed at planned A&P.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'Planned A&P delivers the reach/frequency the planner sized for.',
            'No competitor pulse displaces share-of-voice during the window.',
          ],
          doesNotAssume: [
            'A specific media split — this is a spend-retention projection, not a media plan.',
            'Connected promo holdout data — none is wired yet.',
          ],
          math: `retention_full_ap = baseline + ${baseLift.toFixed(1)} pp.`,
          illustrative: true,
        },
        {
          id: 'cut-30',
          title: '30% A&P cut',
          subtitle: `${drv} runs with 30% less A&P; reach and frequency decay.`,
          directional:
            'A 30% A&P cut decays reach and frequency, shaving the driver lift roughly in proportion to that decay.',
          effectValue: `+${Math.max(baseLift - apDecay * 3, 0).toFixed(1)} pp spend retention`,
          effectKind: 'risk',
          confidenceReason:
            'Decay applied as a linear toy (apDecay × cut_units); the slope has not been validated against a real reach/freq study.',
          confidence: 'Low',
          inputs: DRIVER_INPUTS,
          assumes: [
            'Reach and frequency decay linearly with the A&P cut over the planning window.',
            'No reallocation lifts a peer driver to offset the cut here.',
          ],
          doesNotAssume: [
            'A non-linear decay floor — that needs a real curve fit.',
            'That the cut frees A&P for a more productive driver — outside this prompt.',
          ],
          math: `retention_cut = baseline + max(${baseLift.toFixed(1)} − ${apDecay} × 3, 0) pp; apDecay slope is illustrative.`,
          illustrative: true,
        },
      ];
    case 'add-competitor-response':
      return [
        {
          id: 'status-quo',
          title: 'Status quo (no competitor lift)',
          subtitle: `${drv} runs against the current competitor pulse in ${mustDo}.`,
          directional:
            'Baseline competitive set; the driver carries the planned lift.',
          effectValue: `+${baseLift.toFixed(1)} pp spend retention`,
          effectKind: 'hold',
          confidence: 'Medium',
          confidenceReason:
            'Baseline assumes competitor share-of-voice stays flat during the window.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'No competitor steps up media or shelf pressure in the focus markets.',
            'Planned reach and frequency hold.',
          ],
          doesNotAssume: [
            'A competitor counter-pulse — that is the alternative variant below.',
            'Connected competitive media data — none is wired yet.',
          ],
          math: `retention_status_quo = baseline + ${baseLift.toFixed(1)} pp.`,
          illustrative: true,
        },
        {
          id: 'competitor-lift',
          title: 'Competitor steps up',
          subtitle: `A competitor lifts media and shelf pressure in the focus markets.`,
          directional:
            'A competitor pulse compresses our advantage in the focus markets; the lift shrinks to a defended-share level.',
          effectValue: `+${Math.max(baseLift - competitorPressure, 0).toFixed(1)} pp spend retention`,
          effectKind: 'risk',
          confidence: 'Low',
          confidenceReason:
            'Competitor pressure parameter is an illustrative absorption; the actual compression depends on the specific competitor move.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'A competitor pulse hits the focus markets during the activation window.',
            'Linear absorption — the competitor pressure shaves the driver lift directly.',
          ],
          doesNotAssume: [
            'A specific competitor or media format — modelled as a single absorption term.',
            'Cross-market spillover — modelled inside focus markets only.',
          ],
          math: `retention_competitor = baseline + max(${baseLift.toFixed(1)} − ${competitorPressure}, 0) pp.`,
          illustrative: true,
        },
      ];
    case 'alternative-driver':
      return [
        {
          id: 'this-driver',
          title: `This driver (${drv})`,
          subtitle: `Keep A&P behind ${drv} inside ${mustDo}.`,
          directional:
            'Baseline this-driver lift — the spend stays where it currently sits in the planner.',
          effectValue: `+${baseLift.toFixed(1)} pp spend retention`,
          effectKind: 'hold',
          confidence: 'Medium',
          confidenceReason:
            'Elasticity prior is brand-level; the activation playbook is known for this driver.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'The driver carries the lift it was scoped to deliver in the planner.',
            'No reallocation pressure from finance during the window.',
          ],
          doesNotAssume: [
            'A specific peer driver — the alternative is the variant below.',
            'Connected outcome data — none is wired yet.',
          ],
          math: `retention_this_driver = baseline + ${baseLift.toFixed(1)} pp.`,
          illustrative: true,
        },
        {
          id: 'peer-driver',
          title: `Peer driver inside ${mustDo}`,
          subtitle: `Shift A&P to a peer driver inside the same Must-Do.`,
          directional:
            'A peer driver inside the same Must-Do may absorb the spend with a different — possibly higher, possibly lower — lift profile.',
          effectValue: `+${(baseLift + bundlingUplift).toFixed(1)} pp spend retention`,
          effectKind: 'lift',
          confidence: 'Low',
          confidenceReason:
            'The peer-driver uplift parameter is a linear toy. A real comparison needs both drivers measured under matched conditions.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'The peer driver shares enough focus markets that the shift is operationally feasible.',
            'Linear uplift β stands in for the peer-vs-this differential.',
          ],
          doesNotAssume: [
            'A specific peer driver identity — selecting one is a planner choice.',
            'That this-driver volume is recoverable later — the shift is treated as one-way for this window.',
          ],
          math: `retention_peer_driver = baseline + ${baseLift.toFixed(1)} + β = ${(baseLift + bundlingUplift).toFixed(1)} pp; β (peer differential) = ${bundlingUplift}.`,
          illustrative: true,
        },
      ];
    case 'in-year-since-last-quarter':
      // No variant set — the page hands off to the committed decision's
      // in-year diff (or an empty state if no decision exists yet).
      return [];
    default:
      return [
        {
          id: 'concentrate',
          title: 'Concentrate within focus markets',
          subtitle: `Hold ${drv} spend inside the existing focus markets for ${mustDo}.`,
          directional:
            'Smaller absolute lift but tighter execution risk — keeps the activation inside teams that already ran the playbook.',
          effectValue: `+${baseLift.toFixed(1)} pp spend retention`,
          effectKind: 'hold',
          confidence: 'Medium',
          confidenceReason:
            'Elasticity prior is from a brand-level note, not a desk-level holdout. Markets are known; risk is execution-bound.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'Focus markets remain the bulk of the occasion volume during the activation window.',
            'No new competitor pulse displaces shelf in tier-1 cities.',
            'The signature serve trained in pilot venues holds past week 4.',
          ],
          doesNotAssume: [
            'A national rollout — this variant explicitly stays inside the focus market list.',
            'Bundling uplift — that is the alternative variant below.',
            'Connected promo holdout data — none is wired yet.',
          ],
          math: `retention_concentrate = baseline + ${baseLift.toFixed(1)} pp; elasticity prior α = ${elasticityPrior}, applied flat across focus markets.`,
          illustrative: true,
        },
        {
          id: 'extend',
          title: 'Extend to adjacent markets',
          subtitle: `Widen the ${drv} footprint into adjacent markets that didn't run the pilot.`,
          directional:
            'Bigger upside if the activation travels, real risk if the prior was tied to the pilot markets that already over-indexed.',
          effectValue: `+${(baseLift + elasticityPrior * 8 + bundlingUplift).toFixed(1)} pp spend retention`,
          effectKind: 'lift',
          confidence: 'Low',
          confidenceReason:
            'Elasticity prior is being extrapolated outside the pilot set; bundling uplift is a linear toy with no validated coefficient yet.',
          inputs: DRIVER_INPUTS,
          assumes: [
            'Elasticity prior holds outside the pilot markets at the same magnitude.',
            'Adjacent markets have a comparable on-premise footprint to the focus set.',
            'Linear bundling adjacency holds — bundle uplift compounds rather than substitutes.',
          ],
          doesNotAssume: [
            'A specific media split — this is a spend-retention projection, not a media plan.',
            'A bottom-up elasticity per ZIP — the prior is a single brand-level number.',
            'That existing focus-market wins persist if spend is pulled to fund the extension.',
          ],
          math: `retention_extend = baseline + ${baseLift.toFixed(1)} + α·8 + β = ${(baseLift + elasticityPrior * 8 + bundlingUplift).toFixed(1)} pp; α (elasticity) = ${elasticityPrior}, β (bundling) = ${bundlingUplift}.`,
          illustrative: true,
        },
      ];
  }
}

function buildFindingVariants(
  scope: FindingScope,
  findingTitle: string | null,
): Variant[] {
  const occasionLabel = scope.occasion ?? 'the exposed occasion';
  const brandLabel = scope.brand ?? 'the in-scope brand';
  const findingSummary = findingTitle?.trim() ?? null;
  // Discount-vs-bundle math:
  //   discount_retention(d%) = baseline + α · d
  //   bundle_retention       = baseline + β · (mixer_share − threshold)
  // baseline = 0pp (we report deltas vs the baseline plan); α = 0.9
  // is the illustrative elasticity prior we use elsewhere; β = 0.72
  // captures the linear bundling uplift carried over from the earlier
  // simulation pane. mixer_share assumed at 0.6 and threshold at 0.5
  // so the bundle gets a +0.072 lift over the 15% discount baseline.
  const discountPct = 15;
  const alpha = 0.9;
  const beta = 0.72;
  const baseline = 4; // shelf-only retention floor (illustrative)
  const discount_lift = baseline + alpha * discountPct;
  const bundle_lift = baseline + beta * discountPct + 4; // +4 pp for serve

  if (scope.prompt === 'discount-vs-bundle') {
    return [
      {
        id: 'discount',
        title: `Promote a ${discountPct}% discount`,
        subtitle: `Apply a ${discountPct}% shelf discount on ${brandLabel} during ${occasionLabel}.`,
        directional:
          'Predictable short-term spend retention from buyers already in the occasion. Margin pressure is the trade.',
        effectValue: `+${discount_lift.toFixed(1)} pp spend retention`,
        effectKind: 'hold',
        confidence: 'Low',
        confidenceReason:
          'Elasticity prior is brand-level, not promo-holdout grade. The reading would tighten with a real Don Julio (or in-scope brand) promo holdout for this occasion.',
        inputs: [
          {
            label: 'Loyalty cohort flows',
            source: 'runs/loyalty_panel.csv (loyalty asset)',
          },
          {
            label: 'Brand-level elasticity prior',
            source: 'runs/elasticity_note.md (elasticity asset)',
          },
          {
            label: 'Occasion volume shares',
            source: 'runs/occasion_mix.json (occasion_share asset)',
          },
        ],
        assumes: [
          `${discountPct}% is the salient promo depth in ${occasionLabel}.`,
          'Elasticity is symmetric to the prior — buyers respond to discount as the note predicts.',
          findingSummary
            ? `The finding "${findingSummary}" is the right scoping for the simulation.`
            : 'The scoped finding is the right framing for the simulation.',
        ],
        doesNotAssume: [
          'A cross-channel promo holdout — none is wired yet, so the prediction interval is missing.',
          'That competitor promos hold the same depth in the same week.',
          'Margin impact — that needs the finance overlay, not in scope here.',
        ],
        math: `discount_retention = baseline (${baseline}) + α·d = ${baseline} + ${alpha}·${discountPct} = ${discount_lift.toFixed(1)} pp.`,
        illustrative: true,
      },
      {
        id: 'bundle',
        title: 'Pair with a mixer + serve bundle',
        subtitle: `Bundle ${brandLabel} with a mixer and a serve format for ${occasionLabel}.`,
        directional:
          'Slower setup, but the serve-led bundle protects perceived value better than a flat discount.',
        effectValue: `+${bundle_lift.toFixed(1)} pp spend retention`,
        effectKind: 'lift',
        confidence: 'Low',
        confidenceReason:
          'Bundling uplift is a linear toy (β) carried from the earlier simulation pane. Real reading requires a serve-format A/B against the discount.',
        inputs: [
          {
            label: 'Occasion volume shares',
            source: 'runs/occasion_mix.json (occasion_share asset)',
          },
          {
            label: 'Brand-level elasticity prior',
            source: 'runs/elasticity_note.md (elasticity asset)',
          },
          {
            label: 'Research finding context',
            source: findingSummary
              ? `Research brief finding #${scope.findingIndex + 1}: ${findingSummary.slice(0, 80)}…`
              : `Research brief finding #${scope.findingIndex + 1}`,
          },
        ],
        assumes: [
          `The mixer + serve combo is recognisable in ${occasionLabel}.`,
          'Linear bundling adjacency holds — the bundle adds, not substitutes.',
          'The bundle stays available in the same channels where the discount would land.',
        ],
        doesNotAssume: [
          'A specific mixer SKU — that depends on the activation partner.',
          'A real bundling coefficient β — the value above is illustrative.',
          'Long-tail repeat purchase — this measures the in-window spend retention only.',
        ],
        math: `bundle_retention = baseline (${baseline}) + β·d + serve_uplift (4) = ${baseline} + ${beta}·${discountPct} + 4 = ${bundle_lift.toFixed(1)} pp.`,
        illustrative: true,
      },
    ];
  }

  // Generic counterfactual fallback when the prompt isn't one we
  // template explicitly. We still render ≥2 honest variants rather
  // than dropping back into a hardcoded preview.
  return [
    {
      id: 'a',
      title: `Run variant A of ${scope.promptLabel}`,
      subtitle:
        'First defensible framing of the counterfactual, scoped to the finding.',
      directional:
        'Smaller shift — keeps the activation inside the channels the finding already covers.',
      effectValue: '+5.0 pp spend retention',
      effectKind: 'hold',
      confidence: 'Low',
      confidenceReason:
        'No connected outcome data for this prompt yet — the projection is an elasticity prior, not a measurement.',
      inputs: [
        {
          label: 'Research finding context',
          source: findingSummary
            ? `Research brief finding #${scope.findingIndex + 1}: ${findingSummary.slice(0, 80)}…`
            : `Research brief finding #${scope.findingIndex + 1}`,
        },
        {
          label: 'Brand-level elasticity prior',
          source: 'runs/elasticity_note.md (elasticity asset)',
        },
      ],
      assumes: [
        'Elasticity prior is the right starting point for this prompt.',
        'The finding scope is stable across the simulation window.',
      ],
      doesNotAssume: [
        'A specific activation channel — left for the analyst.',
        'Promo holdout data — none is wired yet.',
      ],
      math: 'variant_a = baseline (4) + α·1 = 5.0 pp, α = 1 (elasticity prior, illustrative).',
      illustrative: true,
    },
    {
      id: 'b',
      title: `Run variant B of ${scope.promptLabel}`,
      subtitle:
        'Second defensible framing — extends scope to an adjacent occasion or channel.',
      directional:
        'Bigger directional lift, with adjacency risk — the prior was not measured outside the finding scope.',
      effectValue: '+8.5 pp spend retention',
      effectKind: 'lift',
      confidence: 'Low',
      confidenceReason:
        'Extension multiplier is a linear toy applied on top of the prior. Validate before committing.',
      inputs: [
        {
          label: 'Research finding context',
          source: findingSummary
            ? `Research brief finding #${scope.findingIndex + 1}: ${findingSummary.slice(0, 80)}…`
            : `Research brief finding #${scope.findingIndex + 1}`,
        },
        {
          label: 'Occasion volume shares',
          source: 'runs/occasion_mix.json (occasion_share asset)',
        },
      ],
      assumes: [
        'The adjacency holds — adjacent occasions respond similarly to the prior.',
        'Linear extension is a defensible first cut for the prompt.',
      ],
      doesNotAssume: [
        'A measured adjacency coefficient — the value is illustrative.',
        'That the finding scope transfers cleanly to adjacent channels.',
      ],
      math: 'variant_b = baseline (4) + α·1 + γ·3.5 = 8.5 pp, γ = 1 (adjacency multiplier, illustrative).',
      illustrative: true,
    },
  ];
}

type ScopeMbpDescriptor = {
  mbpName: string;
  mustDo: string;
  driver: string;
};

function ScopeCard({
  scope,
  findingTitle,
  mbpDescriptor,
}: {
  scope: Scope;
  findingTitle: string | null;
  mbpDescriptor: ScopeMbpDescriptor | null;
}) {
  if (scope.kind === 'driver') {
    const segments = mbpDescriptor
      ? [mbpDescriptor.mbpName, mbpDescriptor.mustDo, mbpDescriptor.driver]
          .filter(Boolean)
          .join(' · ')
      : null;
    return (
      <FocusCard tone="muted" className="border-dashed">
        <div className="grid gap-2">
          <div className="flex flex-wrap items-center gap-2">
            <Badge
              variant="outline"
              className="border-slate-300 bg-white text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600"
            >
              Scope: planning context
            </Badge>
            <Badge
              variant="outline"
              className="border-amber-300 bg-amber-50 text-[10px] font-semibold uppercase tracking-[0.18em] text-amber-800"
            >
              Illustrative
            </Badge>
          </div>
          {segments ? (
            <p className="text-[13px] leading-snug text-slate-900">
              <span className="font-semibold text-slate-950">{segments}</span>
            </p>
          ) : (
            <p className="text-[13px] leading-snug text-slate-800">
              Driver:{' '}
              <span className="font-semibold text-slate-950">
                {scope.driverLabel}
              </span>
              {scope.mustDoLabel ? (
                <>
                  {' · Must-Do: '}
                  <span className="font-semibold text-slate-950">
                    {scope.mustDoLabel}
                  </span>
                </>
              ) : null}
            </p>
          )}
          {/* Active study question is intentionally suppressed for
              driver-scoped counter-scenarios — the MBP descriptor is
              the working scope, not the underlying study question. */}
        </div>
      </FocusCard>
    );
  }
  if (scope.kind === 'finding') {
    return (
      <FocusCard tone="muted" className="border-dashed">
        <div className="grid gap-2">
          <div className="flex flex-wrap items-center gap-2">
            <Badge
              variant="outline"
              className="border-slate-300 bg-white text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600"
            >
              Scope: research finding
            </Badge>
            <Badge
              variant="outline"
              className="border-amber-300 bg-amber-50 text-[10px] font-semibold uppercase tracking-[0.18em] text-amber-800"
            >
              Illustrative
            </Badge>
            <span className="text-[10px] font-mono uppercase tracking-wider text-slate-500">
              prompt · {scope.prompt}
            </span>
          </div>
          <p className="text-[13px] leading-snug text-slate-800">
            Finding #{scope.findingIndex + 1}
            {findingTitle ? (
              <>
                {' · '}
                <span className="font-semibold text-slate-950">
                  {findingTitle.length > 140
                    ? findingTitle.slice(0, 137) + '…'
                    : findingTitle}
                </span>
              </>
            ) : null}
          </p>
          <div className="flex flex-wrap gap-2 text-[12px] text-slate-700">
            <span>
              Occasion:{' '}
              <span className="font-semibold text-slate-950">
                {scope.occasion ?? '—'}
              </span>
            </span>
            <span>
              Brand:{' '}
              <span className="font-semibold text-slate-950">
                {scope.brand ?? '—'}
              </span>
            </span>
          </div>
        </div>
      </FocusCard>
    );
  }
  return null;
}

function VariantsGrid({ variants }: { variants: Variant[] }) {
  if (variants.length === 0) {
    return (
      <FocusCard tone="muted" className="border-dashed">
        <p className="text-[12px] leading-snug text-slate-600">
          The current scope didn&apos;t resolve to any counterfactual variants
          yet. Worker B will broaden the variant catalog when POST
          /counterfactuals lands.
        </p>
      </FocusCard>
    );
  }
  const baseline = variants[0];
  return (
    <div className="grid gap-3 md:grid-cols-2">
      {variants.map((variant, idx) => (
        <VariantCard
          key={variant.id}
          variant={variant}
          baseline={idx === 0 ? null : baseline}
        />
      ))}
    </div>
  );
}

function VariantCard({
  variant,
  baseline,
}: {
  variant: Variant;
  baseline: Variant | null;
}) {
  const deltaLabel = baseline ? formatDeltaVsBaseline(variant, baseline) : null;
  return (
    <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-950/[0.03]">
      <header className="flex flex-wrap items-start justify-between gap-2">
        <div>
          <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">
            Variant
          </span>
          <h3 className="mt-1 text-base font-semibold tracking-tight text-slate-950">
            {variant.title}
          </h3>
          <p className="mt-1 text-[12px] leading-snug text-slate-600">
            {variant.subtitle}
          </p>
        </div>
        <div className="flex flex-col items-end gap-1">
          <Badge
            variant="outline"
            className={cn(
              'border text-[10px] font-semibold uppercase tracking-[0.16em]',
              effectToneClass(variant.effectKind),
            )}
          >
            {variant.effectValue}
          </Badge>
          {deltaLabel ? (
            <Badge
              variant="outline"
              className={cn(
                'border text-[10px] font-semibold uppercase tracking-[0.16em]',
                effectToneClass(variant.effectKind),
              )}
              title="Change versus the first variant on this page"
            >
              {deltaLabel}
            </Badge>
          ) : null}
          {variant.illustrative ? (
            <Badge
              variant="outline"
              className="border-amber-300 bg-amber-50 text-[10px] font-semibold uppercase tracking-[0.16em] text-amber-800"
            >
              Illustrative
            </Badge>
          ) : null}
        </div>
      </header>

      <p className="mt-3 inline-flex items-start gap-2 rounded-2xl border border-slate-200 bg-slate-50/80 px-3 py-2 text-[12px] leading-snug text-slate-700">
        <Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-500" />
        {variant.directional}
      </p>

      <div className="mt-4 grid gap-1">
        <span className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">
          Confidence
        </span>
        <span
          className={cn(
            'inline-flex w-fit items-center rounded-full border px-2 py-0.5 text-[11px] font-semibold',
            confidenceToneClass(variant.confidence),
          )}
        >
          {variant.confidence} — {variant.confidenceReason}
        </span>
      </div>

      <div className="mt-4 grid gap-2">
        <span className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">
          Inputs (real sources)
        </span>
        <ul className="grid gap-1.5">
          {variant.inputs.map((input) => (
            <li
              key={input.label}
              className="flex items-start gap-2 text-[12px] leading-snug text-slate-700"
            >
              <FileSearch className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-500" />
              <span>
                <span className="font-semibold text-slate-900">
                  {input.label}
                </span>{' '}
                <span className="text-slate-500">· {input.source}</span>
              </span>
            </li>
          ))}
        </ul>
      </div>

      <details className="mt-4 rounded-2xl border border-slate-200 bg-slate-50/80 p-3 text-[12px] text-slate-700">
        <summary className="cursor-pointer select-none text-[11px] font-semibold uppercase tracking-wider text-slate-600">
          What this assumes / doesn&apos;t assume
        </summary>
        <div className="mt-3 grid gap-3">
          <div>
            <div className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">
              Assumes
            </div>
            <ul className="mt-1 grid gap-1">
              {variant.assumes.map((item) => (
                <li
                  key={item}
                  className="flex items-start gap-2 leading-snug"
                >
                  <CheckCircle2 className="mt-0.5 h-3 w-3 shrink-0 text-emerald-600" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <div className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">
              Does not assume
            </div>
            <ul className="mt-1 grid gap-1">
              {variant.doesNotAssume.map((item) => (
                <li
                  key={item}
                  className="flex items-start gap-2 leading-snug"
                >
                  <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0 text-orange-500" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="rounded-xl border border-slate-200 bg-white px-3 py-2 font-mono text-[11px] leading-relaxed text-slate-700">
            {variant.math}
          </div>
        </div>
      </details>
    </article>
  );
}

function DisclosureBlock({
  variants,
  scope,
}: {
  variants: Variant[];
  scope: Scope;
}) {
  if (variants.length === 0) return null;
  const winner = variants.reduce<Variant | null>(
    (best, v) => (best == null ? v : bestEffect(v, best)),
    null,
  );
  return (
    <PaneCard
      title="Readout"
      meta="Illustrative projection"
      description="Side-by-side counterfactual readout. Print the math, name the inputs, and surface the assumes/doesn't-assume before treating any number as decision-grade."
    >
      <p className="text-sm font-medium text-slate-900">
        {winner ? (
          <>
            {winner.title}{' '}
            <span className="font-normal text-slate-600">leads</span>{' '}
            {winner.effectValue.replace(/^\+?/, '+')} on spend retention versus
            the other variant, under the illustrative math printed in each
            card.
          </>
        ) : (
          'No variant resolved for the current scope.'
        )}
      </p>
      <p className="mt-2 text-[12px] text-slate-600">
        Prediction interval: not yet estimated. The right rail names the data
        we would need to estimate one honestly for this scope.
      </p>
      <p className="mt-2 text-[11px] uppercase tracking-wider text-slate-400">
        Scope · {scope.kind}
      </p>
    </PaneCard>
  );
}

function ActionBar({
  onValidatePromo,
  onCommitDecision,
  disabled,
  validateState,
  commitState,
}: {
  onValidatePromo: () => void;
  onCommitDecision: () => void;
  disabled: boolean;
  validateState: ValidateState;
  commitState: CommitState;
}) {
  const validatePending = validateState.kind === 'pending';
  const commitPending = commitState.kind === 'pending';
  const submitting = validatePending || commitPending;
  return (
    <div className="rounded-3xl border border-slate-900 bg-slate-950 p-5 text-slate-50 shadow-sm">
      <div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-center">
        <div>
          <h3 className="text-sm font-semibold tracking-tight">
            Make the projection actionable
          </h3>
          <p className="mt-1 text-[12px] leading-snug text-slate-300">
            Validate the chosen variant against connected promo data, or
            commit it as a decision so the in-year query can later say what
            changed.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2 sm:justify-end">
          <button
            type="button"
            onClick={onValidatePromo}
            disabled={disabled || submitting}
            aria-label="Validate the chosen counterfactual variant against connected promo data"
            className="inline-flex h-10 items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 text-[12px] font-semibold text-white shadow-sm transition-colors hover:bg-white/15 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Send className="h-3.5 w-3.5" />
            {validatePending
              ? 'Sending validation task…'
              : 'Validate against promo data'}
          </button>
          <button
            type="button"
            onClick={onCommitDecision}
            disabled={disabled || submitting}
            aria-label="Commit the chosen counterfactual variant as a decision"
            className="inline-flex h-10 items-center gap-2 rounded-full bg-blue-500 px-4 text-[12px] font-semibold text-white shadow-sm transition-colors hover:bg-blue-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <CheckCircle2 className="h-3.5 w-3.5" />
            {commitState.kind === 'pending' && commitState.stage === 'counterfactual'
              ? 'Saving counterfactual…'
              : commitState.kind === 'pending'
                ? 'Committing decision…'
                : 'Commit as decision'}
          </button>
        </div>
      </div>
      {validateState.kind === 'success' ? (
        <div className="mt-3 flex flex-wrap items-center gap-2 rounded-2xl border border-emerald-500/40 bg-emerald-500/10 px-3 py-2 text-[12px] text-emerald-100">
          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-300" />
          <span>
            Created validation task{' '}
            <span className="font-mono text-emerald-200">
              {validateState.taskId.slice(0, 16)}…
            </span>
          </span>
          <Link
            href={`/assets/${validateState.assetKeyEncoded}`}
            className="ml-auto inline-flex items-center gap-1 rounded-full bg-emerald-400/20 px-2 py-0.5 text-[11px] font-semibold text-emerald-100 hover:bg-emerald-400/30"
          >
            Open task asset
            <ArrowRight className="h-3 w-3" />
          </Link>
        </div>
      ) : null}
      {validateState.kind === 'error' ? (
        <p className="mt-3 rounded-2xl border border-orange-500/40 bg-orange-500/10 px-3 py-2 text-[12px] text-orange-100">
          Validation task failed: {validateState.message}
        </p>
      ) : null}
      {commitState.kind === 'error' ? (
        <p className="mt-3 rounded-2xl border border-orange-500/40 bg-orange-500/10 px-3 py-2 text-[12px] text-orange-100">
          Commit failed: {commitState.message}
        </p>
      ) : null}
    </div>
  );
}

function InYearHandoff({
  studyId,
  driverSlug,
  driverLabel,
}: {
  studyId: string;
  driverSlug: string;
  driverLabel: string;
}) {
  const [state, setState] = useState<
    | { kind: 'pending' }
    | { kind: 'found'; decisionId: string; recommendation: string }
    | { kind: 'empty' }
    | { kind: 'error'; message: string }
  >({ kind: 'pending' });

  useEffect(() => {
    let cancelled = false;
    wb.assets({ kind: 'decision' })
      .then((res) => {
        if (cancelled) return;
        const match = pickDecisionForDriver(res.assets, driverSlug);
        if (!match) {
          setState({ kind: 'empty' });
          return;
        }
        const md = match.metadata ?? {};
        const decisionId =
          (typeof md.decision_id === 'string' && md.decision_id) ||
          match.asset_key.at(-1) ||
          '';
        const recommendation =
          typeof md.recommendation === 'string' && md.recommendation
            ? md.recommendation
            : 'Committed decision';
        setState({ kind: 'found', decisionId, recommendation });
      })
      .catch((err) => {
        if (cancelled) return;
        setState({
          kind: 'error',
          message: err instanceof Error ? err.message : String(err),
        });
      });
    return () => {
      cancelled = true;
    };
  }, [driverSlug]);

  if (state.kind === 'pending') {
    return (
      <FocusCard tone="muted" className="border-dashed">
        <p className="text-[13px] leading-snug text-slate-600">
          Checking for a committed decision on {driverLabel}…
        </p>
      </FocusCard>
    );
  }
  if (state.kind === 'error') {
    return (
      <FocusCard tone="muted" className="border-dashed">
        <p className="text-[13px] leading-snug text-orange-700">
          Could not load decisions ({state.message}).
        </p>
      </FocusCard>
    );
  }
  if (state.kind === 'empty') {
    return (
      <FocusCard tone="muted" className="border-dashed">
        <div className="grid gap-2">
          <h3 className="text-sm font-semibold text-slate-950">
            No committed decision yet for {driverLabel}.
          </h3>
          <p className="text-[13px] leading-snug text-slate-700">
            Commit a decision from one of the other stress-tests first. The
            in-year diff compares fresh evidence against what was captured at
            commit time, so it needs a committed decision to compare against.
          </p>
          <div className="flex flex-wrap gap-2">
            <Link
              href={withStudy('/growth-driver', studyId)}
              className="inline-flex h-9 items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 text-[12px] font-medium text-slate-700 shadow-sm hover:border-slate-300 hover:bg-slate-50"
            >
              Open growth-driver planner
              <ArrowRight className="h-3 w-3" />
            </Link>
          </div>
        </div>
      </FocusCard>
    );
  }
  const decisionHref = `/decision/${state.decisionId}?study=${studyId}`;
  return (
    <FocusCard className="grid gap-3">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <h3 className="text-sm font-semibold text-slate-950">
            Open the in-year diff on the committed decision.
          </h3>
          <p className="mt-1 text-[13px] leading-snug text-slate-700">
            {state.recommendation}
          </p>
        </div>
      </div>
      <p className="text-[12px] leading-snug text-slate-500">
        The decision page surfaces the in-year evidence diff (added /
        invalidated / shifted) against the snapshot taken at commit time.
      </p>
      <div>
        <Link
          href={decisionHref}
          className="inline-flex h-10 items-center gap-2 rounded-full bg-slate-950 px-4 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-slate-800"
        >
          Open decision
          <ArrowRight className="h-3.5 w-3.5" />
        </Link>
      </div>
    </FocusCard>
  );
}

// Pick the most recently committed decision asset bound to `driverSlug`.
function pickDecisionForDriver(
  assets: AssetSummary[],
  driverSlug: string,
): AssetSummary | null {
  let best: AssetSummary | null = null;
  let bestAt = '';
  for (const a of assets) {
    if (a.kind !== 'decision') continue;
    const md = a.metadata ?? {};
    const scope = (md.scope ?? {}) as Record<string, unknown>;
    if (typeof scope.driver_id !== 'string' || scope.driver_id !== driverSlug) {
      continue;
    }
    const committedAt =
      typeof md.committed_at === 'string' ? md.committed_at : '';
    if (best == null || committedAt > bestAt) {
      best = a;
      bestAt = committedAt;
    }
  }
  return best;
}

function EmptyState({ detail }: { detail: string | null }) {
  return (
    <FocusCard tone="muted" className="border-dashed">
      <div className="grid gap-3">
        <div className="flex items-center gap-2">
          <Info className="h-4 w-4 text-slate-500" />
          <h3 className="text-sm font-semibold text-slate-950">
            Open this page with scope.
          </h3>
        </div>
        <p className="text-[13px] leading-snug text-slate-700">
          /simulation runs a counterfactual against a scoped target. Open it
          from one of the two source surfaces so the page knows what to
          stress-test:
        </p>
        <ul className="grid gap-2 text-[13px] text-slate-700">
          <li className="flex items-start gap-2">
            <Beaker className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-500" />
            <span>
              From <strong>/growth-driver</strong>, pick a driver and use
              &ldquo;Stress-test growth driver&rdquo;. That hands /simulation a{' '}
              <code className="rounded bg-slate-100 px-1 py-0.5 font-mono text-[11px]">
                driver
              </code>{' '}
              and{' '}
              <code className="rounded bg-slate-100 px-1 py-0.5 font-mono text-[11px]">
                must_do
              </code>{' '}
              param pair.
            </span>
          </li>
          <li className="flex items-start gap-2">
            <Compass className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-500" />
            <span>
              From <strong>/research</strong>, open a finding and click{' '}
              &ldquo;Run counter-scenario&rdquo;. That hands /simulation a{' '}
              <code className="rounded bg-slate-100 px-1 py-0.5 font-mono text-[11px]">
                finding
              </code>
              ,{' '}
              <code className="rounded bg-slate-100 px-1 py-0.5 font-mono text-[11px]">
                prompt
              </code>{' '}
              (and any occasion/brand the page could derive).
            </span>
          </li>
        </ul>
        {detail ? (
          <p className="text-[12px] leading-snug text-slate-500">
            Active study question: {detail}
          </p>
        ) : null}
        <div className="flex flex-wrap gap-2">
          <Link
            href={withStudy('/growth-driver', null)}
            className="inline-flex h-9 items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 text-[12px] font-medium text-slate-700 shadow-sm hover:border-slate-300 hover:bg-slate-50"
          >
            Open /growth-driver
            <ArrowRight className="h-3 w-3" />
          </Link>
          <Link
            href={withStudy('/research', null)}
            className="inline-flex h-9 items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 text-[12px] font-medium text-slate-700 shadow-sm hover:border-slate-300 hover:bg-slate-50"
          >
            Open /research
            <ArrowRight className="h-3 w-3" />
          </Link>
        </div>
      </div>
    </FocusCard>
  );
}

function Toast({
  title,
  body,
  onClose,
}: {
  title: string;
  body: string;
  onClose: () => void;
}) {
  return (
    <div
      role="status"
      aria-live="polite"
      className="pointer-events-none fixed inset-x-0 bottom-6 z-50 flex justify-center px-4"
    >
      <div className="pointer-events-auto flex max-w-md items-start gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-lg shadow-slate-950/10">
        <HelpCircle className="mt-0.5 h-4 w-4 shrink-0 text-blue-500" />
        <div className="min-w-0">
          <p className="text-sm font-semibold text-slate-950">{title}</p>
          <p className="mt-0.5 text-[12px] leading-snug text-slate-600">
            {body}
          </p>
        </div>
        <button
          type="button"
          onClick={onClose}
          aria-label="Dismiss toast"
          className="ml-2 inline-flex h-6 items-center rounded-full border border-slate-200 bg-white px-2 text-[11px] font-medium text-slate-600 shadow-sm hover:border-slate-300 hover:bg-slate-50"
        >
          Dismiss
        </button>
      </div>
    </div>
  );
}

function bestEffect(a: Variant, b: Variant): Variant {
  const av = effectMagnitude(a);
  const bv = effectMagnitude(b);
  return av >= bv ? a : b;
}

function effectMagnitude(variant: Variant): number {
  const match = variant.effectValue.match(/(-?\d+(?:\.\d+)?)/);
  if (!match) return 0;
  const v = Number(match[1]);
  return Number.isFinite(v) ? v : 0;
}

// Compose a "−1.0 vs baseline" / "+0.5 vs baseline" badge for variants
// after the first, using the same units that the absolute pill carries
// (e.g. "pp spend retention").
function formatDeltaVsBaseline(variant: Variant, baseline: Variant): string {
  const a = effectMagnitude(baseline);
  const b = effectMagnitude(variant);
  const delta = b - a;
  if (!Number.isFinite(delta)) return '';
  // Pull the trailing units from the baseline's effectValue —
  // everything after the leading number — so a delta on
  // "+6.0 pp spend retention" reads "−1.0 pp vs baseline" (not just
  // "−1.0").
  const tail = baseline.effectValue.replace(/^[+\-]?\d+(\.\d+)?\s*/, '').trim();
  const unit = tail.split(' ')[0] ?? '';
  const sign = delta >= 0 ? '+' : '−';
  const magnitude = Math.abs(delta).toFixed(1);
  return unit
    ? `${sign}${magnitude} ${unit} vs baseline`
    : `${sign}${magnitude} vs baseline`;
}

function pickWinner(variants: Variant[]): Variant | null {
  if (variants.length === 0) return null;
  return variants.reduce<Variant>((best, v) => bestEffect(v, best), variants[0]);
}

function variantToBody(v: Variant): Record<string, unknown> {
  return {
    id: v.id,
    title: v.title,
    subtitle: v.subtitle,
    directional: v.directional,
    effect_value: v.effectValue,
    effect_kind: v.effectKind,
    confidence: v.confidence,
    confidence_reason: v.confidenceReason,
    math: v.math,
    illustrative: v.illustrative,
    inputs: v.inputs,
    assumes: v.assumes,
    does_not_assume: v.doesNotAssume,
  };
}

// Scope is intentionally minimal — the backend models accept study_id
// plus driver_id or finding_id. Empty scopes are gated upstream by the
// onCommit/onValidate guards.
function buildCounterfactualScope(
  studyId: string,
  scope: Scope,
): CounterfactualScopeBody {
  if (scope.kind === 'driver') {
    return { study_id: studyId, driver_id: scope.driverSlug };
  }
  if (scope.kind === 'finding') {
    return {
      study_id: studyId,
      finding_id: `finding-${scope.findingIndex}`,
    };
  }
  return { study_id: studyId };
}

function buildDecisionScope(studyId: string, scope: Scope): DecisionScopeBody {
  return buildCounterfactualScope(studyId, scope) as DecisionScopeBody;
}

function buildTaskScope(studyId: string, scope: Scope): TaskScopeBody {
  if (scope.kind === 'driver') {
    return { study_id: studyId, driver_id: scope.driverSlug };
  }
  if (scope.kind === 'finding') {
    return { study_id: studyId, finding_id: `finding-${scope.findingIndex}` };
  }
  return { study_id: studyId };
}

function buildCounterfactualPrompt(
  scope: Scope,
  findingTitle: string | null,
  winner: Variant,
): string {
  if (scope.kind === 'driver') {
    return `Stress-test ${scope.driverLabel}${
      scope.mustDoLabel ? ` for ${scope.mustDoLabel}` : ''
    } — ${winner.title}`;
  }
  if (scope.kind === 'finding') {
    const subject = findingTitle?.trim() || `Finding #${scope.findingIndex + 1}`;
    return `Counter-scenario (${scope.promptLabel}) on "${subject}" — ${winner.title}`;
  }
  return winner.title;
}

function buildRecommendation(scope: Scope, winner: Variant): string {
  // Compose a single recommendation sentence from the variant's title +
  // the directional effect sentence — the two carry the directional
  // commitment and the "why" we want preserved in the decision asset.
  const scopeNote =
    scope.kind === 'driver'
      ? ` for ${scope.driverLabel}${
          scope.mustDoLabel ? ` (${scope.mustDoLabel})` : ''
        }`
      : scope.kind === 'finding'
        ? ` for ${scope.promptLabel}${
            scope.brand && scope.occasion
              ? ` on ${scope.brand} in ${scope.occasion}`
              : scope.occasion
                ? ` in ${scope.occasion}`
                : ''
          }`
        : '';
  return `${winner.title}${scopeNote}. ${winner.directional}`;
}

function deriveConfidenceBlock(winner: Variant) {
  // Until we wire real holdout data, we collapse the variant's pill to a
  // 3-bucket holds_in / of so the decision asset still carries the same
  // honesty contract that /research findings use (e.g. "3 of 4
  // scenarios agree"). High → 3/3, Medium → 2/3, Low → 1/3.
  const ofTotal = 3;
  const holdsIn =
    winner.confidence === 'High'
      ? 3
      : winner.confidence === 'Medium'
        ? 2
        : 1;
  const sentence = winner.confidenceReason;
  return {
    sentence,
    holds_in: holdsIn,
    of: ofTotal,
    label: winner.confidence,
  };
}

function deriveFragileAssumption(scope: Scope, winner: Variant): string {
  if (winner.assumes.length === 0) return '';
  if (scope.kind === 'driver') {
    return `Holds only if: ${winner.assumes[0]}`;
  }
  return winner.assumes[0];
}

function buildValidateDescription(
  scope: Scope,
  findingTitle: string | null,
): string {
  if (scope.kind === 'driver') {
    const must = scope.mustDoLabel ? ` (${scope.mustDoLabel})` : '';
    return `Validate the ${scope.driverLabel}${must} stress-test against connected promo data before any spend moves.`;
  }
  if (scope.kind === 'finding') {
    const subject =
      findingTitle?.trim() || `finding #${scope.findingIndex + 1}`;
    const where = scope.occasion ? ` in ${scope.occasion}` : '';
    return `Validate the ${scope.promptLabel} counter-scenario for ${subject}${where} against connected promo data.`;
  }
  return 'Validate the active counterfactual against connected promo data.';
}

function effectToneClass(kind: Variant['effectKind']): string {
  switch (kind) {
    case 'lift':
      return 'border-emerald-200 bg-emerald-50 text-emerald-700';
    case 'hold':
      return 'border-blue-200 bg-blue-50 text-blue-700';
    case 'hedge':
      return 'border-amber-200 bg-amber-50 text-amber-700';
    case 'risk':
      return 'border-orange-200 bg-orange-50 text-orange-700';
    default:
      return 'border-slate-200 bg-slate-50 text-slate-700';
  }
}

function confidenceToneClass(level: ConfidenceLevel): string {
  switch (level) {
    case 'High':
      return 'border-emerald-200 bg-emerald-50 text-emerald-700';
    case 'Medium':
      return 'border-yellow-200 bg-yellow-50 text-yellow-700';
    case 'Low':
    default:
      return 'border-orange-200 bg-orange-50 text-orange-700';
  }
}
